name: CI/CD Pipeline for Airflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest    #sai

    env:
      DOCKER_IMAGE: santosh0788/airflow-docker:1.0
      DOCKER_TAG: latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE }} .

    # Step 4: Push the Docker image to DockerHub
    - name: Push Docker image
      run: |
        docker push ${{ env.DOCKER_IMAGE }}